version: '3'
services:
# SERVICE DE L"APPLI FRONT END
  vuejs_app:
    container_name: vuejs_app
    image: ndemeyvan/vuejs-frontend:v1.0.0
    ports:
      - 80:80
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30
