name: Build Containers for Prod & Push to Dockerhub

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - ci_cd_vuejs

jobs:
  build-and-deploy-Vuejs-frontEnd:
    name: Build and Deploy Vuejs Front-end
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        run: echo The tag is 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ndemeyvan/vuejs-frontend
        dockerfile: Dockerfile
        tags: latest